# Generated by Django 2.2.12 on 2020-04-22 15:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'Firmwares',
            },
        ),
        migrations.CreateModel(
            name='FirmwareVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'firmware_versions',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'vendors',
            },
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_vendor_name'),
        ),
        migrations.AddField(
            model_name='firmwareversion',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Device'),
        ),
        migrations.AddField(
            model_name='firmware',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FirmwareVersion'),
        ),
        migrations.AddField(
            model_name='device',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Vendor'),
        ),
        migrations.AddConstraint(
            model_name='firmwareversion',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, version=None), name='version_not_null'),
        ),
        migrations.AddConstraint(
            model_name='firmwareversion',
            constraint=models.UniqueConstraint(fields=('version',), name='unique_version'),
        ),
        migrations.AddConstraint(
            model_name='firmware',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, data=None), name='data_not_null'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, name=None), name='name_not_null'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_device_name'),
        ),
    ]
