# Generated by Django 3.0.4 on 2020-04-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('parent_id', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='devices',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, parent_id=None), name='parent_id_not_null'),
        ),
        migrations.AddConstraint(
            model_name='devices',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
    ]
