# Generated by Django 3.0.4 on 2020-04-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20200421_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='vendor_id',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='firmwareversion',
            old_name='device_id',
            new_name='device',
        ),
    ]
